---
apiVersion: v1
kind: Service
metadata:
  name: foreman-proxy
  namespace: "{{ project_name }}"
  labels:
    app: foreman-proxy
spec:
  selector:
    app: foreman-proxy
  ports:
    - protocol: TCP
      targetPort: 8080
      name: port-8080-tcp
      port: 8080
