---
apiVersion: batch/v1
kind: Job
metadata:
  name: foreman-proxy-register
  namespace: "{{ project_name }}"
  labels:
    app: foreman-proxy-register
spec:
  template:
    metadata:
      labels:
        app: foreman-proxy-register
    spec:
      restartPolicy: Never
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
      containers:
        - name: foreman-proxy-register
          image: "{{ registry }}/foreman-proxy:latest"
          command:
            - ansible-playbook
            - /root/register.yaml
