---
apiVersion: v1
kind: Deployment
metadata:
  name: qpid
  namespace: "{{ project_name }}"
  labels:
    app: qpid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qpid
  template:
    metadata:
      labels:
        app: qpid
    spec:
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
      containers:
        - name: qpid
          image: "{{ registry }}/qpid:latest"
