---
- name: foreman routes
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.route.yaml') | from_yaml }}"
  with_items:
    - foreman-https
    - foreman-http-pub
    - foreman-http-pulp
