---
apiVersion: v1
kind: Service
metadata:
  name: puppet
  namespace: "{{ project_name }}"
  labels:
    app: puppet
spec:
  selector:
    app: puppet
  ports:
    - protocol: TCP
      targetPort: 8140
      name: port-8140-tcp
      port: 8140

