---
apiVersion: v1
kind: Deployment
metadata:
  name: puppet
  namespace: "{{ project_name }}"
  labels:
    app: puppet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puppet
  template:
    metadata:
      labels:
        app: puppet
    spec:
      containers:
        - name: puppet
          securityContext: {}
          state: present
          volumeMounts:
            - readOnly: false
              mountPath: /etc/puppet
              name: puppet-data
          image: puppet/puppetserver
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
      volumes:
        - name: puppet-data
          persistentVolumeClaim:
            claimName: puppet-data
