---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: "{{ project_name }}"
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      targetPort: 27017
      name: port-27017-tcp
      port: 27017
