---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: foreman-developer
subjects:
- kind: User
  name: developer
roleRef:
  kind: ClusterRole
  name: foreman-developer
  apiGroup: rbac.authorization.k8s.io
