---
apiVersion: v1
kind: Service
metadata:
  name: candlepin
  namespace: "{{ project_name }}"
  labels:
    app: candlepin
spec:
  selector:
    app: candlepin
  ports:
    - protocol: TCP
      targetPort: 8080
      name: port-8080-tcp
      port: 8080
