---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: "{{ project_name }}"
  labels:
    app: memcached
spec:
  selector:
    app: memcached
  ports:
    - name: memcached
      port: 11211
      targetPort: 11211
