---
apiVersion: v1
kind: Service
metadata:
  name: content-server
  namespace: "{{ project_name }}"
  labels:
    app: content-server
spec:
  selector:
    app: content-server
  ports:
    - protocol: TCP
      targetPort: 80
      name: port-80-tcp
      port: 80
    - protocol: TCP
      targetPort: 443
      name: port-443-tcp
      port: 443
