---
apiVersion: v1
kind: Deployment
metadata:
  name: pulp-celerybeat
  namespace: "{{ project_name }}"
  labels:
    app: pulp-celerybeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulp-celerybeat
  template:
    metadata:
      labels:
        app: pulp-celerybeat
    spec:
      containers:
        - name: pulp-celerybeat
          securityContext: {}
          state: present
          image: "{{ registry }}/pulp-celerybeat:latest"
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
