---
apiVersion: v1
kind: Deployment
metadata:
  name: pulp-resource-manager
  namespace: "{{ project_name }}"
  labels:
    app: pulp-resource-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulp-resource-manager
  template:
    metadata:
      labels:
        app: pulp-resource-manager
    spec:
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
      containers:
        - name: pulp-resource-manager
          securityContext: {}
          state: present
          image: "{{ registry }}/pulp-resource-manager:latest"
