---
apiVersion: v1
kind: Deployment
metadata:
  name: squid
  namespace: "{{ project_name }}"
  labels:
    app: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
        - name: squid
          securityContext: {}
          state: present
          ports:
            - protocol: TCP
              containerPort: 3128
          image: "{{ registry }}/squid:latest"
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
