---
apiVersion: v1
kind: Deployment
metadata:
  name: httpd
  namespace: "{{ project_name }}"
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
      volumes:
        - name: httpd-config
          configMap:
            name: "httpd-configs"
        - name: certs
          secret:
            secretName: certs
            items:
              - path: katello-default-ca.crt
                key: ca.crt
              - path: server.crt
                key: server.crt
        - name: keys
          secret:
            secretName: keys
            items:
              - path: server.key
                key: server.key
      containers:
        - name: httpd
          image: "manageiq/httpd:latest"
          command:
            - httpd
            - "-D"
            - FOREGROUND
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: httpd-config
              mountPath: "/etc/httpd/conf.d"
            - readOnly: true
              mountPath: /etc/pki/katello/private
              name: keys
            - readOnly: true
              mountPath: /etc/pki/katello/certs
              name: certs
